server:
  port: 22288

spring:
  application:
    name: spiritsword-rpc-server

spiritsword:
  rpc:
    server:
      boss: 1
      worker: 3
      backlog: 128
    client:
      id: default-client-id
      worker: 3
      host: 127.0.0.1
      port: 6666