spring:
  application:
    name: spiritsword-rpc

spiritsword:
  rpc:
    server:
      port: 22188
      boss: 1
      worker: 3
      backlog: 128
    client:
      id: default-client-id
      worker: 3
      host: 127.0.0.1